import { Card, CardBody, Text } from "@chakra-ui/react";
import React from "react";
import Head from "next/head";

const blog = ({ blog }) => {
  return (
    <div>
      <Head>
        <title>Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Card>
        {blog.map((el) => (
          <CardBody
            key={el.id}
            style={{
              border: "2px solid black",
              textAlign: "center",
              margin: "20px",
              borderRadius: "20px",
            }}
          >
            <h1 style={{ fontSize: "25px" }}>{el.title}</h1>
            <Text>{el.body}</Text>
          </CardBody>
        ))}
      </Card>
    </div>
  );
};

export async function getServerSideProps() {
  const res = await fetch(`http://localhost:8080/blog`);
  let data = await res.json();
  return {
    props: {
      blog: data,
    },
  };
}

export default blog;
