export const JOB_POST_PENDING = "JOB_POST_PENDING";
export const JOB_POST_FAILURE = "JOB_POST_FAILURE";
export const POST_JOB_POST_SUCESSE = "POST_JOB_POST_SUCESSE";
export const GET_JOB_POST_SUCESSE = "GET_JOB_POST_SUCESSE";
