export const COFFEE_API_SUCCESS = "COFFEE_API_SUCCESS";
export const EMPLOYEE_API_SUCCESS = "EMPLOYEE_API_SUCCESS";
export const RESTAURANT_API_SUCCESS = "RESTAURANT_API_SUCCESS";
export const API_REQUEST = "API_REQUEST";
export const API_FAIL = "API_FAIL";
